name: Generate and Translate PDFs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-translate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: jahwag/latex-openai:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upgrade TeX Live using update-tlmgr-latest
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
          sh update-tlmgr-latest.sh --update

      - name: Set TeXLive CTAN mirror
        run: tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet

      - name: Update TeXLive packages
        run: tlmgr update --self --all

      - name: Install required LaTeX packages
        run: tlmgr install lineno xcolor

      - name: Create output directory
        run: mkdir -p output

      - name: Compile LaTeX to PDF (English)
        run: |
          pdflatex -interaction=nonstopmode -output-directory=output resume.tex
          mv output/resume.pdf output/resume-eng.pdf

      - name: Translate .tex file to Swedish
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 scripts/translate_resume.py

      - name: Print resume-sve.tex for debugging
        run: cat resume-sve.tex

      - name: Compile LaTeX to PDF (Swedish)
        run: |
          pdflatex -interaction=nonstopmode -output-directory=output resume-sve.tex
          mv output/resume-sve.pdf output/resume-sve.pdf

      - name: Upload PDFs to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cp output/*.pdf gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update generated PDFs"
          git push
