name: Generate and Translate PDFs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-translate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container:
      image: jahwag/latex-openai:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p output

      - name: Compile LaTeX to PDF (English)
        run: |
          pdflatex -interaction=nonstopmode -output-directory=output resume.tex
          mv output/resume.pdf output/resume-eng.pdf

      - name: Translate .tex file to Swedish
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 -c "
          from openai import OpenAI
          import os
          
          api_key = os.getenv('OPENAI_API_KEY')
          client = OpenAI(api_key=api_key)
          
          with open('resume.tex', 'r') as file:
              english_text = file.read()
          
          response = client.chat.completions.create(
              model='gpt-3.5-turbo',
              messages=[
                  {'role': 'system', 'content': 'You are a translator. Translate only the main body text of the LaTeX document to Swedish. Ignore any LaTeX commands or formatting'},
                  {'role': 'user', 'content': english_text}
              ]
          )
          
          swedish_text = response.choices[0].message.content.strip()
          
          with open('resume-sve.tex', 'w') as file:
              file.write(swedish_text)
          "

      - name: Print resume-sve.tex for debugging
        run: cat resume-sve.tex

      - name: Compile LaTeX to PDF (Swedish)
        run: |
          pdflatex -interaction=nonstopmode -output-directory=output resume-sve.tex
          mv output/resume-sve.pdf output/resume-sve.pdf

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdfs
          path: output/*.pdf

